{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opscode.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name | default "opscode" }}
  labels:
    {{- include "opscode.labels" . | nindent 4 }}
{{- end }}
